package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "retro",
    srcs = [
        "app.cc",
        "panel.cc",
        "screen.cc",
        "table.cc",
        "table_window.cc",
        "window.cc",
        "dialog.cc",
    ],
    hdrs = [
        "app.h",
        "panel.h",
        "screen.h",
        "table.h",
        "table_window.h",
        "window.h",
        "dialog.h",
    ],
    linkopts = select({
        "@platforms//os:linux": [
            "-lncursesw",
            "-lpanelw",
        ],
        "//conditions:default": [
            "-lncurses",
            "-lpanel",
        ],
    }),
    copts = ["-std=c++20"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:str_format",
        "@coroutines//:co",
        "@coroutines//co:co_cpp20",
    ],
)

cc_test(
    name = "cpp20_test",
    size = "small",
    srcs = ["cpp20_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":retro",
        "@com_google_googletest//:gtest_main",
    ],
)
